### ISSUE TITLE
Has the new export mechanism changed?

### ISSUE THREAD

**Issue by TheDeadCalledLu** [cuddlyogre/ExportLDraw#42]
In the old version of the plugin, whether to export parts to dat files depends on whether the mesh is selected and its "ldraw_export_polygons" custom attribute
In the new version, there is no "ldraw_export_polygons" in the monkey sample file, replaced by a "ldraw_props", but the monkey.dat can still be exported
what happened?
![image](https://github.com/cuddlyogre/ExportLDraw/assets/73033381/4225b3df-4591-4621-b14a-66e672b1489b)
![image](https://github.com/cuddlyogre/ExportLDraw/assets/73033381/4bae1b75-8e9a-46d7-9cd7-0416893a1a5e)
![image](https://github.com/cuddlyogre/ExportLDraw/assets/73033381/3d2fb067-e83d-475b-b4d0-458d176db47e)
![image](https://github.com/cuddlyogre/ExportLDraw/assets/73033381/10e58340-a80f-4673-9e8c-c66359a9ed34)
The first picture is the parts that can be exported in the old version
The second picture is the monkey sample in the new version
The third picture is the ldraw part using the import function in the new version
By the way, when the new version exports the part of the third picture, its mesh data will not be exported (see the fourth picture)

**Comment by cuddlyogre** [comment]
Apologies for that. The export mechanism was one of the first things I wrote for this project, and in python as whole, so I had to update a few things. Other than bug fixes, the main thing I did was to add an **ldraw_props** data structure that encapsulates the LDraw properties and an LDraw panel for objects so you could change them in one place.

The new workflow is:

Set the header properties in the active object under **Header**. Some items may still need to be added manually, but this takes care of most of them.

Set the color and filename of subfile lines (objects not marked **Export polygons**) under **Part Attributes**.

For objects you wish to export as polygons check **Export polygons**.

**Export precision** to set how many decimal places are used in matrix elements for **Export polygons** items. My parts were initially rejected on submission to the parts library for having more than 2 so that's the rationale for the choice of default.

![image](https://github.com/cuddlyogre/ExportLDraw/assets/3506795/2eb91d9f-155b-407e-af9f-019f094a96e1)

**Comment by TheDeadCalledLu** [comment]
Thanks, it looks better than the old version
